### PR TITLE
manage tags from RSS sources

### PR DESCRIPTION
**Pull request by ghost**
- Allow to get tags from the RSS sources and send them to Diaspora*
- remove separators inside tags breaking tags in Diaspora (e.g #open source => #opensource)

### CODE REVIEW

**Comment by ghost** [comment]
Just updated the PR removing unneeded repetitions of replace(), one call being enough to remove multiple times of a character in the same string.

**Comment by Debakel** [comment]
Is this the normal way to set tags in RSS feeds? Maybe we should also include categories [http://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt](http://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt).

**Comment by ghost** [comment]
Hi, 

Not sure what you mean by "set tags in RSS feed" because my PR only extracts the tags from the RSS feed thanks to feedparser https://pythonhosted.org/feedparser/reference-feed-tags.html I'm not setting anything except feeding the hashtags list with the extracted tags.

**Comment by Debakel** [comment]
Sorry, i was confused because `tags` are called `categories` in the [RSS specification](http://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt). Thanks for contributing @chaica :)

**Comment by ghost** [comment]
Thanks for merging it :)

**Pull request merged**
